<?php
/**
 * Eranium Filtergen
 * @copyright Eranium B.V.
 * @license Mozilla Public License 2.0
 * @link https://github.com/eranium/filtergen
 */

declare(strict_types=1);

namespace Eranium\Filtergen\Formatters;

require_once __DIR__.'/FormatterInterface.php';

class AristaFormatter implements FormatterInterface
{
    /**
     * Generates Arista styled prefix lists, takes output generated by Filtergen.
     * @param  array  $prefixes
     * @param  array  $options
     * @return string
     */
    public static function format(array $prefixes, array $options = []): string
    {
        $sequence = 1;
        $prefixList = '';
        foreach ($prefixes as $prefix) {
            $prefixList .= 'seq '.$sequence.' permit '.$prefix.PHP_EOL;
            $sequence++;
        }
        return $prefixList;
    }
}
